### ISSUE TITLE
Cannot build R repo with repo2docker 2022.02.0

### ISSUE THREAD

**Issue by pierrepo** [jupyterhub/repo2docker#1152]
### Bug description

It looks like that compiling a R environment with repo2docker 2022.02.0 is failing.

#### Former and expected behaviour

With repo2docker 2021.08.0:

```bash
$ jupyter-repo2docker --version
2021.08.0
$ jupyter-repo2docker https://github.com/plasmabio/template-r/
Picked Git content provider.
Clonage dans '/tmp/repo2docker42mzl1lz'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 7 (delta 0), pack-reused 0
Dépaquetage des objets: 100% (11/11), 4.12 Kio | 602.00 Kio/s, fait.
Using CondaBuildPack builder
Step 1/65 : FROM buildpack-deps:bionic
 ---> 0dd28a87935f
[...]
    To access the notebook, open this file in a browser:
        file:///home/pierre/.local/share/jupyter/runtime/nbserver-515-open.html
    Or copy and paste this URL:
        http://127.0.0.1:52047/?token=0ae72921d81b6cfc932876b78a26b9a265b59d2a2a91c9e5
```

Everything is fine. Please note the repo https://github.com/plasmabio/template-r/ is a basic R environment we are using for our project [Plasma](https://github.com/plasmabio/plasma) for a couple of years now and it used to play nicely with repo2docker.

#### Actual behaviour

With repo2docker 2022.02.0:

```bash
$ jupyter-repo2docker --version
2022.02.0
$ jupyter-repo2docker https://github.com/plasmabio/template-r/
Picked Git content provider.
Clonage dans '/tmp/repo2docker7ko1gxnk'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 7 (delta 0), pack-reused 0
Dépaquetage des objets: 100% (11/11), 4.12 Kio | 527.00 Kio/s, fait.
Traceback (most recent call last):
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/semver.py", line 42, in parse_version
    return semver.VersionInfo.parse(vstr)
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/semver.py", line 726, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError:  is not valid SemVer string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/bin/jupyter-repo2docker", line 8, in <module>
    sys.exit(main())
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/__main__.py", line 418, in main
    r2d.start()
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/app.py", line 830, in start
    self.build()
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/app.py", line 780, in build
    picked_buildpack.render(), extra=dict(phase="building")
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/base.py", line 478, in render
    for user, script in self.get_preassemble_scripts():
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/conda/__init__.py", line 401, in get_preassemble_scripts
    scripts.extend(self.get_env_scripts())
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/conda/__init__.py", line 373, in get_env_scripts
    scripts += rstudio_base_scripts(self.r_version)
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/buildpacks/_r_base.py", line 17, in rstudio_base_scripts
    if V(r_version) <= V("4.1"):
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/repo2docker/semver.py", line 48, in parse_version
    return semver.VersionInfo.parse(vstr)
  File "/home/pierre/.soft/miniconda3/envs/repo2docker/lib/python3.9/site-packages/semver.py", line 726, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: .0.0 is not valid SemVer string
```

We obtain the exact same behaviour with [mybinder](https://mybinder.org/v2/gh/plasmabio/template-r/master):

![image](https://user-images.githubusercontent.com/733861/164308171-2284e7b0-d7fc-4da8-a2dc-20b97e7a2f01.png)

### Your personal set up

 - OS: Linux Ubuntu 20.04
 - Docker version: 20.10.14, build a224086
 - repo2docker version : 2022.02.0

**Comment by manics** [comment]
This should've been fixed by https://github.com/jupyterhub/repo2docker/pull/1141.

Please can you try installing the `main` branch and tell us if the issue still occurs?

**Comment by pierrepo** [comment]
Thanks for your suggestion @manics. So I did:

```bash
$ python -m pip install git+https://github.com/jupyterhub/repo2docker
$ jupyter-repo2docker --version
2022.02.0+19.g1d218af
$ jupyter-repo2docker https://github.com/plasmabio/template-r/
Picked Git content provider.
Clonage dans '/tmp/repo2dockerjktt371q'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 7 (delta 0), pack-reused 0
Dépaquetage des objets: 100% (11/11), 4.12 Kio | 602.00 Kio/s, fait.
Using CondaBuildPack builder
Step 1/64 : FROM buildpack-deps:bionic
 ---> 0dd28a87935f
[...]
    To access the notebook, open this file in a browser:
        file:///home/pierre/.local/share/jupyter/runtime/nbserver-521-open.html
    Or copy and paste this URL:
        http://127.0.0.1:48421/?token=e52c735fdb02cb0c880c522867e9a4f7067a8d30dc92cf80
```
And it worked fine :tada: Thank you very much for your help :pray: @manics 

Do you have any idea when a new release of repo2docker that incorporates the fix https://github.com/jupyterhub/repo2docker/pull/1141 will be published?

I guess you can also close the present issue.
