### ISSUE TITLE
Launching notebooks with `--editable` flag is not working

### ISSUE THREAD

**Issue by nasiegel88** [jupyterhub/repo2docker#1345]
I have no issue launching repo2docker local or remote repos, however when I launch a notebook with `--editable` I receive error messages. I have also tried using the abbreviation `-E` to no avail.

```shell
jupyter-repo2docker https://github.com/norvig/pytudes

Works fine
```

```shell
$ jupyter-repo2docker https://github.com/norvig/pytudes --editable

Picked Git content provider.
Cloning into '/tmp/repo2dockerauf4zpim'...
remote: Enumerating objects: 271, done.
remote: Counting objects: 100% (271/271), done.
remote: Compressing objects: 100% (265/265), done.
remote: Total 271 (delta 5), reused 202 (delta 4), pack-reused 0
Receiving objects: 100% (271/271), 58.65 MiB | 3.36 MiB/s, done.
Resolving deltas: 100% (5/5), done.
Reusing existing image (r2dhttps-3a-2f-2fgithub-2ecom-2fnorvig-2fpytudes37bd115), not building./srv/conda/envs/notebook/lib/python3.10/subprocess.py:961: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
Traceback (most recent call last):
  File "/usr/local/bin/repo2docker-entrypoint", line 114, in <module>
    main()
  File "/usr/local/bin/repo2docker-entrypoint", line 58, in main
    child = subprocess.Popen(
  File "/srv/conda/envs/notebook/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/srv/conda/envs/notebook/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '--editable'
CONTAINER FINISHED RUNNING.
```

**Comment by manics** [comment]
Arguments for repo2docker need to be placed before the repo path (`jupyter-repo2docker --editable https://github.com/norvig/pytudes`). Arguments after the repo are passed to the startup command.
