### ISSUE TITLE
jupyter_offlinenotebook missing for custom environment

### ISSUE THREAD

**Issue by tomyun** [jupyterhub/repo2docker#961]
### Bug description

When using a custom version of python by setting up a dependency in `environment.yml`, `jupyter_offlinenotebook` is installed in a directory not picked up by the custom environment, leading to an error logged by Jupyter.

Here is the error shown up when launching Jupyter for a docker image with Python 3.8:
```
[W 16:53:26.843 NotebookApp] Error loading server extension jupyter_offlinenotebook
    Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.8/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/srv/conda/envs/notebook/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_offlinenotebook'
```

#### Expected behaviour
`jupyter_offlinenotebook` should be installed in a directory used by custom environment (i.e. `/srv/conda/envs/notebook/lib/python3.8/site-packages` in this case).

#### Actual behaviour
`jupyter_offlinenotebook` is installed in the default directory (`/srv/conda/envs/notebook/lib/python3.7/site-packages`).

### How to reproduce
1. Define a custom Python version in `environment.yml`:
```yml
dependencies:
  - python=3.8
```
2. Build a docker image and run.
3. Error shown up in the log.

### Your personal set up
 - OS: macOS 10.15
 - Docker version: 19.03.12
 - repo2docker version: 0.11.0+134.g64371cb

**Comment by manics** [comment]
I wasn't able to reproduce this:
https://gist.github.com/manics/e16a6d746862015c2f92930e092a5b5f

Note there was a warning about needing to rebuild jupyterlab (https://github.com/jupyterhub/mybinder.org-deploy/issues/1607), but I think that's a separate issue.

Can you provide more details on your setup?

**Comment by tomyun** [comment]
I should have mentioned that I was using JuliaProjectTomlBuildPack. You could trigger this by having an empty `Project.toml` in `binder` directory where `environment.yml` is located.
